project:
  type: website
  output-dir: docs

website:
  title: "Automation Management"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: introduction.qmd
      - text: "Requirements"
        file: requirements.qmd        

sidebar:
  - title: "Introduction"
    style: "docked"
    background: light
    contents:
      - introduction.qmd
  - title: "Requirements"
    style: "docked"
    background: light
    contents:
      - requirements.qmd      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
